<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>爱弥斯启动器</AssemblyName>
    <Product>爱弥斯启动器</Product>
    <Title>爱弥斯启动器</Title>
    <ApplicationIcon>..\DockPetWin\Resources\App\pet-app-icon.ico</ApplicationIcon>
    <OutputPath>..\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
</Project>
